name: Deployment Notification

on:
  deployment_status:
    types: [created, in_progress, completed, failed]

jobs:
  notify:
    runs-on: ubuntu-latest
    if: github.event.deployment_status.state != 'in_progress'
    steps:
      - name: Notify Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: deployments
          SLACK_COLOR: ${{ github.event.deployment_status.state == 'success' && 'good' || github.event.deployment_status.state == 'failure' && 'danger' || 'warning' }}
          SLACK_TITLE: Deployment ${{ github.event.deployment_status.state }}
          SLACK_MESSAGE: |
            *Environment:* ${{ github.event.deployment.environment }}
            *Repository:* ${{ github.repository }}
            *Commit:* ${{ github.event.deployment.sha }}
            *Status:* ${{ github.event.deployment_status.state }}
            *Deployer:* ${{ github.actor }}
            *Time:* ${{ github.event.deployment_status.updated_at }}
          SLACK_FOOTER: ${{ github.server_url }}/${{ github.repository }}/deployments 